apiVersion: v1
kind: Secret
metadata:
  name: pg-policy-reporter
  namespace: database
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:xSTTskvYD7HH7Jrxf1MqXwPR,iv:oHsQB7QGX4dAqCNp1jo92FyPLfU1LKrOVgi+hCcxz1c=,tag:QZdoJ/5YfsRae61L6YmTdA==,type:str]
  password: ENC[AES256_GCM,data:xizqbbvixQrWQuWTp76GrcU8wsMce1qm3dTiHD5Cm8OqesuK0oHvjmwrNAAYCX0Af5Lw7e33dphyNvhTbffqJg==,iv:NDYfRK3MnAulB3zSbcnex4mEJuF1wHFd/a0wGRtBnrY=,tag:XBmI/kpJxvJicObQXsr88A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka0lqblBjWkJNejhNUkMz
        M0VMNUh2bFFOTS9zVGNoYmNzbEZxeC9BUHhnCldDblJLd1h4VWZCSDBaMExQRDMw
        Qzc3TERPTXFiMkM1YVFwVU55MTRiaEEKLS0tIEtkVnZqQWY1eDFzK09HVmVmeHBZ
        bXpTYmx1UFdmMzJDNUZLc2gzUi9FTm8KjMv+amd77HkBUtvHhE4AcDiKSNo/TInA
        uRhJ9xehvSqHKv+Zy0ZzDmJQBBklYXtZfl3x2qDc92V9HpeN7wPEmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-07T19:42:40Z"
  mac: ENC[AES256_GCM,data:6ueQJGcpZudd4YetF+NoWic4LEbRiXNVa+dGQzIfovFIH/GHXDEQoiqPEOxFyZBqb0Ak59ip0yorum5fzEJTztiZZuwZFEieUlIiMf3Y9lUJYV+Ob4Ld8/pA2ieN8NMZSptAR5+f1IqQw3ZcgOEJDrn/BP8O8YT0zi8Nfkj13tg=,iv:7il7w1Ku0V/TtoP3H8oV7mHQXR1nAJNmWwTpvcHfbIg=,tag:0uNMfxbgZ7saEHhm9kSFJA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
