apiVersion: v1
kind: Secret
metadata:
  name: pg-policy-reporter
  namespace: database
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:YC2pAnM=,iv:R12nyxgyaF1ihaqjHiK5xJyxAV9tbBjZnm/DK+kwTd0=,tag:g0p6tGBsbMFZbM8SDofEeA==,type:str]
  password: ENC[AES256_GCM,data:9zu+UxAJ2yWHtSWU2g3s,iv:0/0HrM2EP5vmvTpTRu6uvU5TFKQvTZ8GhT5HJPHNvyA=,tag:KU8GxCRa/3nYtdmnZKzRaA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBka0lqblBjWkJNejhNUkMz
        M0VMNUh2bFFOTS9zVGNoYmNzbEZxeC9BUHhnCldDblJLd1h4VWZCSDBaMExQRDMw
        Qzc3TERPTXFiMkM1YVFwVU55MTRiaEEKLS0tIEtkVnZqQWY1eDFzK09HVmVmeHBZ
        bXpTYmx1UFdmMzJDNUZLc2gzUi9FTm8KjMv+amd77HkBUtvHhE4AcDiKSNo/TInA
        uRhJ9xehvSqHKv+Zy0ZzDmJQBBklYXtZfl3x2qDc92V9HpeN7wPEmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-06T19:48:41Z"
  mac: ENC[AES256_GCM,data:OyPf0FxzJxRboxLvJyB7A/aFWkpT6AUrEaN1rvH0NoGcNDZC9HTcY26fPTdi9CbuFqWn+q0IQG1qMHj+CRFQK6yd+Wpkw3F223flErc9p3Jk7KX5+SMOJLUgWd1Z54BCljSG3LE4DFNjA7epKUhtNPB+tZqwfdgSzMGwhZrczv0=,iv:MZO1LHfbrxQG6Hiz9yQ8Uw0d88ua7uRIhfRSUyJxIfo=,tag:B08AOJDEfXKtbIJpASVD7w==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
