apiVersion: v1
kind: Secret
metadata:
  name: pg-policy-reporter-s3-secret
  namespace: database
type: Opaque
stringData:
  aws-access-key-id: ENC[AES256_GCM,data:XUwZ+zQgsB+25DI+7dEOtELM1CTSJYleXQ==,iv:ayTjiuUd0k2NSpbLqjLVDHu+pYrqvmDlx5BJ+gNEgxY=,tag:0at2lyOkLMLc4xeK5FhwLg==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:hmrtqzo3acPYUELUB1Nn5t6j2YklxSpfRw7NdnRYTQ==,iv:IuugdnDFMX4mmDPG+vLgZgdRdTBAvJxW+7GqWPKaZCM=,tag:zixcCujJguZRq9l2XcOBqg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ0xVY05QcGxKTnRpdU1l
        d0ErcjgxR1NHdHVyaStnL2dJUElZZHR5ZW1BCmVFNHo1cS9MS05Sbjd5ektHUkRD
        K1crKzU2ZVBYc1cyc1RTZWh0Z21XNkUKLS0tIFVjQlc2ZFh3Ym5Bd1BJdS92WENK
        QU8wTWNRd2dLckdUdnhYZGdsbHRIRTgK8rSJNLk7F9zWyMZTI5yRn5DAc9i00zAC
        QQ1NDziSMGa9IWiPlh7Y1ONbf8QL7eI4I/rs1WDehS63ek1OB/EjXQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-06T19:47:33Z"
  mac: ENC[AES256_GCM,data:LmxPpGKqKGIGbrOfZdV1ZvU8PZkwKct659yDLJZ1W+H72/2+9yfSLiv6MmWLmvMf960DMyVvq/sqkWFIKr7SfTodyytuu71jjzdiYebT7nPX/8OuKObROPkrW1kzXJK9CCVtNsPn0lFQ+7YFmFwVAgjCE1hYHqqDkI6ckmZ/e2w=,iv:VpNK0SjkJlEDmmo+Yoj+ef45dMe0UxPRBuwxFJs/3io=,tag:CXGdWqmawEyqaRbrybJUPA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
