---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    grafana.internal/instance: grafana
spec:
  config:
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      feedback_links_enabled: "false"
      reporting_enabled: "false"
    auth:
      disable_login_form: "false"
      oauth_auto_login: "false"
      signout_redirect_url: "https://authentik.${SECRET_DOMAIN}/application/o/grafana/end-session/"
    auth.anonymous:
      enabled: "false"
    auth.generic_oauth:
      enabled: "true"
      name: "Authentik"
      icon: "signin"
      client_id: "grafana-envoy"
      scopes: "openid profile email groups"
      auth_url: "https://authentik.${SECRET_DOMAIN}/application/o/authorize/"
      token_url: "https://authentik.${SECRET_DOMAIN}/application/o/token/"
      api_url: "https://authentik.${SECRET_DOMAIN}/application/o/userinfo/"
      role_attribute_path: >-
        contains(groups[*], 'grafana-admins') && 'Admin' ||
        contains(groups[*], 'grafana-editors') && 'Editor' ||
        contains(groups[*], 'grafana-viewers') && 'Viewer' ||
        'None'
      role_attribute_strict: "true"
      allow_assign_grafana_admin: "true"
      use_pkce: "true"
    log:
      mode: console
    metrics:
      enabled: "true"
    news:
      news_feed_enabled: "false"
    plugins:
      plugin_admin_enabled: "false"
    security:
      angular_support_enabled: "true"
    server:
      enable_gzip: "true"
      root_url: https://grafana.${SECRET_DOMAIN}
  deployment:
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-admin-password-secret
                      key: GF_SECURITY_ADMIN_PASSWORD
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: authentik-grafana-oidc
                      key: client-secret
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: {drop: ["ALL"]}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
  httpRoute:
    spec:
      hostnames: ["grafana.${SECRET_DOMAIN}"]
      parentRefs:
        - name: envoy-internal
          namespace: network
      rules:
        - backendRefs:
            - name: grafana-service
              port: 3000
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: longhorn-no-backup
  disableDefaultSecurityContext: All