apiVersion: v1
kind: Secret
metadata:
  name: authentik-alertmanager-oidc
  namespace: observability
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:ZhL/PPGlf1b/KiRinMCAeSar8ThMHkUmLvSPmASjCB+0j6eV2Am0Ba+Nst96f6JhkI++hq54yjvcKmNzzI7GKA==,iv:bPS0bXO5Z83lUFoOlXyigdcIjSm8KNYYK4anjsaDzik=,tag:9sJYu9sFXOcv5/OmUOb74A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZS9OUHh5a3dXc21MWlZH
        aEVYa1BUMGU3MGU1dXppdFlpTS9Vc3pvQ0FnCmI3ci8wV3ZRMnB1Y0xmbDRmWElP
        TW5YbFd6STNIcVRwamVhc3VwZkJ1SE0KLS0tIGRZdWdrQWo0MnFSVzVjam5LbmZW
        Y2hyRXZKYVNFWk0xcmRsalVmaDl2MzQK1u1mQ2iuiXnzB45G15gkJKoRGgjMtAQM
        fq4Z2ttQSLwPtaauL9wRrsGLuhCnpEJs1FiDN9nSoB8BFmICuIyMbQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T10:30:06Z"
  mac: ENC[AES256_GCM,data:X97dmC6/bYw1qbAbUgxpdG21l43yrJmpeMiz/nBfYxpwAjKPWq0V00EKKKXHUroONkxV6NS+yzJ68qVk2fehHz+lqOd0uqI7eEw3YPJp7GdMWB0yFqEjfrdE0u4Xk21cPpEix+Y2hPz424br4QX4F45BzUJxuZFj29d677Aebck=,iv:IhUa3j9uXjyD89j1EoV4wVKrbMTf7SeFJoBp+B+JLc0=,tag:GzqEaZJaUddWTjRTt9x2JA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
