apiVersion: v1
kind: Secret
metadata:
  name: authentik-prometheus-oidc
  namespace: observability
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:0LrAWlqtUx1KYXmOAaFct/kg3AZu2GtQ+18Da+elus6CGsQB/aPbQhRCDhUeIdyi8lM1KyPUMx4E5nNIvMdkUw==,iv:UYiuBUsGOJ770F3iCG4oeP2zQh6t9S+ObOfwdPlI2KQ=,tag:y7d1OHumHJBnQC9Pe88FHw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOODN3dVVBVHZ2Q2V2U2hY
        bW9NVDRyTlFDN1JqSDVPSXRMZE5IYVRsZDFjCnV4QlVEc1gxQ0gzY1c5clJYZCtO
        Z2dXb3V4VlpVd3FEdENSZFZ1MWwwY3MKLS0tIG01K25Zc0Z3VHRGY2t3QkswaUxJ
        cTFJSlRJTXZoWEluMFlSakwrVVNGV1EK0UByVsjKM8wzeYsmu7kIjJ03jkj6LDCh
        Ep03ACmWKGIKiy2g3ZHtPoXa57zBtaH51GVoi9DEQLaAbE7Zet3igw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T10:17:40Z"
  mac: ENC[AES256_GCM,data:rjAqlU/mExPAgccA2a68pn4k1EneHGhTBzqfJAdjkfYCmF3n48RyDdi/8Re6j57YMs6WLY+3jVA4t8PE5gqv8ChZLyGhuYbBqLSGm5sRTA/5lOv76+b6/Cqdm1WscuHy9h3oyhPjrUK8ACe6lYynDxoisbM5ZBqm/PNn3PW611E=,iv:Tajmq9Sb1v090AyetFwgCGM3+YFf6S4Cj0areXBwzY4=,tag:dQGPZn45xw8q8dlrotbuYw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
