apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
type: Opaque
stringData:
  pushover_api_token: ENC[AES256_GCM,data:RWXayodtnTPMGmhElyuaAPSv5NpN2jYtKbjm/zGC,iv:BpMLcWvz+LdnXdjAoCke7MGi+fVI+qhNhSc3rVKBaD0=,tag:tbuXsoY2/IbcdBVfbry0wg==,type:str]
  pushover_api_userkey: ENC[AES256_GCM,data:8XNoZEUiBHlfeIXXpSC/Mqu8aa3zuRVjQyhiiqep,iv:tHeHQHInzgm6WyGttz5FEmG1B0qu+dWnpImSEAooN3o=,tag:hM6us71umtNe0MV9TLA2vg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcWFjVTM3UFk5dlkvaWhO
        M20zWmpURjdKMzlTR1p5enZGd0RUNm1sV2drCndsSFBpM092V2ZUMUhGNlZnRm12
        Vjd6TUUvbTBkRStjTGt6NER6VGR6LzQKLS0tIElPVFRHeG13bWNrVFhxL3JFVjVr
        OU5QMFBhaHFnQ09QYmlKZlJkREo1Y0EKKcPx0RU+9WoGGf2G/gbvmmJWlkilbT2o
        2Uf/q61ZkSTYDcxNAAdb2tSEqQLpZi6I+ZDOYXrIocVNqq59LAIuHA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-08T18:43:55Z"
  mac: ENC[AES256_GCM,data:ZHD2lYL3efmqtoW+J4fEwEeZ/51gSHoDlNArd9X4tftyGVtUFgJJwg9y9zc8/9OsHHEkGUVBEd6ekVhQSitP6H3rDtN1G++rmVItVAcdNkTpp7SEeUwewUPXY629U/a4EXGuByrfed0paPw2WMuseImjfz+qDGTlQZ5m8N2kERg=,iv:/ogsXLMzAdDuzUPCANxO+cdljMZhfRp6+Cym1RDtFdg=,tag:mrMIWS2Dm8+r8fhudkkjRQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
