apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
type: Opaque
stringData:
  pushover_api_token: ENC[AES256_GCM,data:l7YeyoIUy+2fC6ovAKWLoOk886+Br4L+lPt0lMvJ,iv:c8t5o+iD+lliC969vhGH2kl31DeST/qKxARBI2vMKA8=,tag:3sfFi/6WhzN9yFlw/MBJLQ==,type:str]
  pushover_api_userkey: ENC[AES256_GCM,data:8XNoZEUiBHlfeIXXpSC/Mqu8aa3zuRVjQyhiiqep,iv:tHeHQHInzgm6WyGttz5FEmG1B0qu+dWnpImSEAooN3o=,tag:hM6us71umtNe0MV9TLA2vg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcWFjVTM3UFk5dlkvaWhO
        M20zWmpURjdKMzlTR1p5enZGd0RUNm1sV2drCndsSFBpM092V2ZUMUhGNlZnRm12
        Vjd6TUUvbTBkRStjTGt6NER6VGR6LzQKLS0tIElPVFRHeG13bWNrVFhxL3JFVjVr
        OU5QMFBhaHFnQ09QYmlKZlJkREo1Y0EKKcPx0RU+9WoGGf2G/gbvmmJWlkilbT2o
        2Uf/q61ZkSTYDcxNAAdb2tSEqQLpZi6I+ZDOYXrIocVNqq59LAIuHA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-07T19:09:18Z"
  mac: ENC[AES256_GCM,data:qvQtcTaHMK+igF1+mFE+cjFQTJHNp+IlE9KCOEvCWfujTo7x8VmFPuXDz5xZRdDR3Yf/aS9aAOxWHKs5Rg/iNvmnQXwNnO3Pmg9pcXlf3FGmWgpM5AI9iKMANemDa2oyNpoMuJqAoFPOPuwtO4qWN5l6c+TYcx2ayAuMgZcOw3s=,iv:g4o9+i+YFM+51j3KVduG4YnJcN63wztQ+0Iib+J21is=,tag:qGzeqGYp0GjGST9nLvLPXg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
