---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: falco

resources:
  - ./falcon-falco-allow-eg-to-k8s-api.yaml
  - ./falco-falco-allow-eg-to-host.yaml