apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-alert
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-metrics-alert
  interval: 1h

  values:
    serviceAccount:
      create: true
      automountToken: false

    server:
      replicaCount: 3

      podDisruptionBudget:
        enabled: true
        minAvailable: 2
        unhealthyPodEvictionPolicy: AlwaysAllow

      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0

      minReadySeconds: 10

      datasource:
        url: http://victoria-logs-server.observability.svc.cluster.local:9428

      notifier:
        url: http://alertmanager-operated.observability.svc.cluster.local:9093

      config:
        alerts:
          groups:
            - name: victoria-logs
              type: vlogs
              interval: 5m
              rules:
                - alert: TooManyErrorLogs
                  expr: 'error | stats count() as error_logs | filter error_logs:>100'
                  for: 5m
                  labels:
                    severity: warning
                  annotations:
                    summary: Too many error logs
                    description: >-
                      More than 100 log entries containing "error" were found
                      during the last 5 minutes.

      route:
        enabled: true
        hostnames:
          - vm-alerts.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network

      podSecurityContext:
        enabled: true

      securityContext:
        enabled: true
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false

      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          memory: 256Mi

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: victoria-metrics-alert

      extraVolumes:
        - name: external-alert-rules
          configMap:
            name: victoria-metrics-alert-rules
      extraVolumeMounts:
        - name: external-alert-rules
          mountPath: /external-rules
          readOnly: true
      extraArgs:
        rule:
          - /external-rules/alert-rules.yaml

    serviceMonitor:
      enabled: true