apiVersion: v1
kind: Secret
metadata:
  name: authentik-vmalert-oidc
  namespace: observability
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:O5Lu8/QaqQw8EfsjpZPEaWvlrovb9UNG4ykRw/nvNwVRKfmROgzHcV5fDRexGbiDTTc9ihDldcKajHuPIySnxA==,iv:/3lXhTTPiEhu90AtEE+DPDYp76nWIRT25qitaFIirZk=,tag:uDDYRFJ8azGqUtPEZpOGIQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsclVrNFp4eFo4d1VyNVpB
        N2dBdnpSWGJ4eUdNdnBuM29oMjhlNlh6ZEc0Ckd1OVpPTXFVaVp3TG1qcnpabnNk
        MGVxS243dnpFR2RlSEdBemNTVEluU3MKLS0tIDZZNGlFQlFneHcvRnVUd05rU0w2
        ekdIQ214M215VGFzTEpZdHQ4WnVxOTQKZ5/xQM78dmhEwWzWcFhwiu8f1EYyRb5/
        xPUx7ihq3GXtcE18iZBaVhMe76fznTgJMVUPa4YIkSFlLqIUaYVVdA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T11:14:45Z"
  mac: ENC[AES256_GCM,data:Y4MpjTmY8XY9lZLGCPu7r1V+CC11AABtMaKXj2oFge3HLtL8PoUrjRAlc7GOko4DCw49sxVuvZWtPpLOjzMdEN03Xc/Y+kMygBYz66eoFIVbvQUQ0WjNlHDnPXp+4jygZ4iliTTSytH6PsODQveCwBue4zLND9/Bd2F8oWdAW+g=,iv:drHWsCYsr+IeIReOzC+s+HDggsRqKDsu3Ej+D15+pYA=,tag:DcsjeKKJh8VGqJLnmsQMwA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
