apiVersion: v1
kind: Secret
metadata:
  name: authentik-alertmanager-oidc
  namespace: auth
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:Wsyxbcia+F+GiesO0P3c5xZsRTO8o5jfwaKDO2ILYbZITOxsflOoke1ooTZjlGHjzQ9K/ZXFfovvql9Tthp7kw==,iv:oyO4JfLIg9jyGQetOIXjWsvhFk925SBalnT6vPeKW9g=,tag:yR4E4UDBHGL9dLwLljBt/w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMFZ1KzZDdG1sNUVLMUhs
        cEQ0SjZlSDBtS0dPbkoxR3lCMzZidkFhZUVFCjNnTloyUGo2WTdIbG05RTlaZ1BZ
        OG9GY29VQW91dnM3T2hKSzFMeXlzMXcKLS0tIFlFWXZNNUhpSEhlbUI4ZVo4U08x
        U1Z4Wk5XQndlaGNhM250UXNTZGRnOGsKqJpW3BU86ucSxYBfvD024jF8SMxVY2+T
        Rfiz8orqsMHrkdNf4NQfPsHJ+Y3Jtpo/tUK+0NPKMzlr3HsJrAHHCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T10:23:09Z"
  mac: ENC[AES256_GCM,data:oEqHBrqtcgwAwcim4PeR5ANwYGFjJgjytJFWqNW2zn9n77ivo1NdKTyIHasEkCJJoLDK+UoS34FbM9at6IRzIzH+yKvX2ZoUF7AwFEJw9vn6SWyNSS1YW1+iWIpd/7y9tT4ZXYytBGZNMELWvDB9uS3VgWqPa57ogkvg5s4lfMI=,iv:hDo6JxRMO6LU7n3TnAley513fUaUZVITW5ZdYb6XI/8=,tag:quMGTS/FiKFjowvOjqOHkw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
