apiVersion: v1
kind: Secret
metadata:
  name: authentik-grafana-oidc
  namespace: auth
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:K92S9rXdxKBqBdJYykd1OKDdkjStq/0YNCtQj6truLp6JIDRhQgu1lj2xwDi+QhW8Mh9doLImA7ZY3b8aiM4qQ==,iv:p5G6keRYBxyQjF9ORGEX02Vwda87gBgh3ZgvDCNgrhg=,tag:3ia2+k13j3jM7jtUkYkhXw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCa080VkdxVHc5TGRXa3FX
        MkliQlFGYVdoR3BGenFzdWdxZmtxbW1WMjM4CkpCRXZKclc4aFNIenlTakY4MmpC
        R0NzZ3hEQzQ1TjV0UUhoWFpqTXN3K1EKLS0tIFArNnhjcFdGY1Z6MERiVEN5anha
        eHR0d0tSVzV1bU5PZ3dDTzFZbGR5aEEKVICWZVU7q4O04VA3qHxWf3J04w1apTjW
        acpIJglq8Zzj6FP6xGEDsCaK6eCb0EgR3WZzjS2keAZ+TMl0zgkQFg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T13:16:11Z"
  mac: ENC[AES256_GCM,data:pJDDOd4oUA9gXcD+X7R/6SiwzltupaapDWQlygHkqDpej9NOnEbdHbjewIf4DdTjk3uvc0lm0c1zHTQST5tCfffcNyGL1j1YOW2pli3LBBA64YHqtJYYJU0TVIBcwrPREVDOMsEHrCyrF6b//OtN1OxKfvvsCzhx/Mns9gbOb5w=,iv:Fu86PBja7YQwyEpTjTKuWT3qIq33yqj2sG3w2sJK27E=,tag:GCYKPw+lUd9i22MaX2u8jQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
