apiVersion: v1
kind: Secret
metadata:
  name: authentik-hubble-oidc
  namespace: auth
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:7Rq59b12fDfx+bFCs8U1hFpSgygwmwMsewQkvrcXOtRGqLlWCZpq58Z8B9oSAlB5eKYYg6hpaKD7M9zuxBBn9g==,iv:fi9/TR6vi+Y4GNwuy7BDo9gpPE//XwkdKJ7cHQolZws=,tag:6djm0SJZ19DM6g92WAn3uw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSWx3VjgzNjMvUG5BSzBu
        OWxBUDNmbUszVzIwT0VydEdJSk5EaWorV1dvClU0UFpPRjYwbGQ2OGc0UjdGU0xv
        SGZtQ3RrV0lNOWtoWVQ1dUo3RENrTDQKLS0tIDZINk1KWU5ObVVlQlFlK1JPd3Rk
        QVRxOEVuMDZkTEVrb0llNjdsWFJHblkKewrkv+zS8tKrG6vAeLol7EJ2ljDDSgpv
        7bdpnJSV0/SvTZkYlj6VZJVMSVF57B6/khlQqCsr0ML+Bk3VQsUuMg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T09:26:24Z"
  mac: ENC[AES256_GCM,data:jmOGdQx2fXL75l364iaK4aOqdeVBpqiAu930DnLTQqiV11NAyZelpJivuKPEKDnVIEgKelF4CJTT4vWhxJ6iimrHkB7gdRS4BHz0YLZ+v41RA3VwkBAfX+xtPcflRz91AMSU1bJnHOC4m7PItwP6mYERsp2mcft4SDzWzVonAgg=,iv:oo3Z13K1dBVj829vtKxqmDJwOHhdAAPHRfD/qtlX5vY=,tag:pPy6z73+tqk/PTZai9b0wA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
