---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./longhorn-oidc.secret.sops.yaml
  - ./policyreporter-oidc.secret.sops.yaml
  - ./hubble-oidc.secret.sops.yaml
  - ./prometheus-oidc.secret.sops.yaml
  - ./alertmanager-oidc.secret.sops.yaml
  - ./victorialogs-oidc.secret.sops.yaml
  - ./vmalert-oidc.secret.sops.yaml