---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-longhorn-oidc
  namespace: auth
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:e1oO38eHLMBYkZaOtpNAGLEsFVf6EuU0AK0GzXM4zaiD8xa9cVC7gxQ9IGT/YzX4GCF3TlxLnssL56UZcZCg7g==,iv:pgGtHkrGr39A5amI+0gvrCxKTa9GjLDLFX3k4Ht0MqY=,tag:wOc95iba6yzMDTgJdBzz0w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOGl0OFNRK2ZlRU1tcTJi
        aUdESmF2V2ZRR0lrMmJnbDVFOXBnOGkwTVhZCmo0R3FERFNSOEcvbGFobFhJeXU4
        dnBaNHE3NkE0YUk3V1dLeTVBRklYSlkKLS0tIDlEbVZtNlg3YU02bDJsVXJ1RWZX
        Q3NwaVNxTmdkVVlUNTNjNFpCVGZ4c0kKXSB9XklY/S7G6tTaPYgaQu9ZBjc0RBen
        cM40hXXZRVWu4NCGC8xSaHt/0f7rHMZ/yomjgsQF5qO6+dQI1e75mA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-21T12:11:28Z"
  mac: ENC[AES256_GCM,data:fI6Wk6iYXlIBh+30pn+AFH7xj//dbnVTuQbbRmeUL9TANmorJfld+rMw53L7Gr791krwA9m2HOdIvTH6sA06dk7iYFdb7CPEh4HpzSTC2K0z2dgKl/53xSAwcTqDiZRsfQLZh81ifuwtYtKY56dk33nYIz7UdLM5g5Rv5o3iqgQ=,iv:hmSwv13laCba9VCWIieLczI2oVNFpCEV8L8kN22idyY=,tag:PL95nf1RiUp+tlmIiJ/l1Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
