apiVersion: v1
kind: Secret
metadata:
  name: authentik-policy-reporter-oidc
  namespace: auth
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:LentqhzQup4oQNSdsxeQy38JbZjmrcuFiHQDZ/nQQ+v+37HgnwDqFlMcF0ERP5PvQxwwg9frAIwFUBWXqJsTBQ==,iv:SiDzUKSEZDsg2ZrIitkPmLQ+ZkIOZ6SBoTqn7HVitM0=,tag:r/xcuhX7ydFlz5/RQBZINg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QVppaHpSUlBVOHMxby94
        V3FQeldtdU9wSDdrZ0VhZVBwalVhbzkxS1RBClFLRjR0eDV3dmFZcVd3UTM3OGlK
        aHRGRGF2d2NTUjVQVTk2b2VSam5kREUKLS0tIEJyNDNIVnA3YWlIUFUwRmorNTEx
        Q3pnTUZhV01RSkNjLzUxNWFpaGh0dU0Kihn9MJNsYag6E2OvDP6YnB9mxSDkxQl6
        owW42Zq47pM4dhf9DRxJpcOScSdrq3f+iSrBA4PIjGyflZmWldMo/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-21T20:41:04Z"
  mac: ENC[AES256_GCM,data:c2jq/AmSNHknF7Sq//qcO1Bq2JSe7IBrpg7CU2vjVAT1heyJhw/jQ5ZzKt/L8fhT5gBXCi/nKHfD+C7i89OTZo0xmji8SfUASgfyU9yhftOyp/h9zmoozOrjS/8oyw+pgaFhoDEJH+uPectPsD6E6s9iqgGYLJf50sibiPWsmUs=,iv:X2VEOcNZxf35m14wyXohXYqkkPPJbN+BLrB4VgvuGvg=,tag:YdCHqcC8unOcxVy5ye+zDA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
