apiVersion: v1
kind: Secret
metadata:
  name: authentik-prometheus-oidc
  namespace: auth
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:O85OnwxGBXDSz6rh60n534hpNSwZM0uW1hZmNV2nFQFPsr+jV5uQhDhct0XdwCsGX+pS5yHNGd9PVpPh8ryLbA==,iv:9WyGzHBMp/Ve1QZIGt3SZEPPmswPXLI7REjzvX7TPnw=,tag:icKYNW4UhX/QtLYCy/GOjw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQU14cDFORWxva2JZQTFT
        M2ptdGtHNFRzZW9GdEtiMWpla0RrclROdFVRCmxMNWg2a3g4ME85RVVNKzN6V2w2
        TytJTHNLbnBqcnVlYkVRYzBLRlg2aHcKLS0tIGJIbzM1L2NST255ZitzVkVaZ3pV
        bzhmVUlicGZDdXJyREpJdVFEZnNZV2cKjkzC2gka7L9s4g4ehaII3aYLA6yVDmJu
        qTSVp8wRsZBurQZx9UVa8nz96gooE3GrYot7gTE7deGvYx9BAUu1uA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T10:14:13Z"
  mac: ENC[AES256_GCM,data:byos1uErlWjk7ITgl7TgllANU6oqlBXCN132zysflTXGokbpw9lmX7PaVkoArCRG+IvnpW0vJVLRXpTsjAkif2lTNyI86YTgkMMQ0JyWHSRCiE/elhvpoIhKT/CUp2KJW1vZEJ+aSQHmq/u3ROej5931PKCaFh4pUCERAHXZup0=,iv:xfICGf9Snr6SpIwjJD1zd5OeIvdFselMq/mCykvJZZ8=,tag:Xo/96Z43+UjYN6Q5qSZA8w==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
