apiVersion: v1
kind: Secret
metadata:
  name: authentik-trek-oidc
  namespace: auth
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:/XtVK0Y6g7BRL6X/Eu5vGfqShlqPXe1fkyvzCKH2D/xkYgX1w469bQsAGNUlH/T1gwAJLhaODdT/zVz3waOFxQ==,iv:Ab8//ygRrTHMXql4qH4u9O/y+aU/INsY3fobMiG6fZo=,tag:/ndC5ohnaOb8xig+xxqt5A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWEpiUVJ5cTJMejR4RzdW
        RWJYTFRidWZEVTlFa2NKanN2WWR5N0hKamhFCmJ6UjRzdmZackI1OVpkSU80T3po
        aThab0lrWnVWZHVIYUwxdFhuTnZnYTgKLS0tIC93YUpvRzREVGtlcUI5emNuUzVv
        cGU4OGllU216YXBabzlJa1owNHlCSk0KaXKss/suRDkCKjKc5ksaD/4j7pkFIeeW
        YvlDxKQ+W3DJCeR2Swrjqdy4H4G7JXZjMeG4o0GYr24DT4KrGG1Kaw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-24T11:00:07Z"
  mac: ENC[AES256_GCM,data:5ccG0VgsbEKWkMfitcVtFS8zc/NNo9i+FXAHeBC9urISwdqi8T1MKWLVhan+LvdhsXkoumW+wOcYgtA4+oRhpBjNBKq+TZuxSWpYIBRiFSaTRo5iLU4pQU1PyZxZWqBKSp7/i2FLikABhsL1+GCNAT0hH+8jdk8yB8prVQJQCAk=,iv:DU0ThcP2++zayIJ7uf1T03kpOn7CuXap1eudsGGL9XU=,tag:8SYfb/eIKE6/pPVFLvq3kw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
