apiVersion: v1
kind: Secret
metadata:
  name: authentik-victorialogs-oidc
  namespace: auth
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:uo6fGw9Va9PKWuurNT4TTjveAYt2+qJozCQ0Pv5RpPPffgDa7yhPvgN5uiPj0L41getQRm5PE8VKwLGDXlFVHA==,iv:4BqgZAAVfd8pZOc1LrwBmsPEClVl30Tms6h3YRW9YtM=,tag:Nf4FXPX96j6XDbZYj/BQsw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRXMvM0xxbU1iN1FqZGl2
        Ukh2dUU3RTdTOHJYQ012NEJ3eHphT2I5NnpZCkpXeVM5U2FQRjhKTk56TGM1UG1w
        bk4xT0N6N2cwck1WZlUwcnpYZ2Z4MzQKLS0tIGQxcUtmZHVSZUQzOFkyRWhEZ2Na
        a1pvN2laT2phVXJTd0JJbFFkT2dqdXMK0ePfBXu0Q6whoPby0dnqpb4zWV/tiUYK
        onDn54HFAZIago+rE7QFWi3HOBdaqmIOwrpocWaNckzOtH8TykulCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T10:35:49Z"
  mac: ENC[AES256_GCM,data:SMFUuS/OFs3u2xmTw3Yj//cx7xXUdiRJs1DcTkGQLR5MefK8uhh0x/KvekOG/B+qfg7IWlRQ71UzvyshS3/KWDK9PaHbqPsg2PEaI/l7U7VlzIT1/Xcwan13ODlgjcMy+9u2loqRrI5PqIPb++UxdHF3Amy5dWY82k9Pc8P8xHs=,iv:Btm0iqRk143RfSgpj7fKGIyIR5DSjMINGF0dGgZEhsc=,tag:EDR92+cEEmEJ4WzbCixc3Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
