apiVersion: v1
kind: Secret
metadata:
  name: authentik-vmalert-oidc
  namespace: auth
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:1YoRD+6VXgsI3FLmPWLYsv3MtHiFyYYFKmCBYXqqcK+VvzOYFwOq0A0uhQbw22/NUIQ/AC4YpWWn4iF8ANuUkQ==,iv:mYBs2apPoM6C7JAg4nqncFEt5Yj14Z2cngNNIFDdRxU=,tag:va31fb7KEni5TcyUWNBJGw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQVg2SzF6bFlMMW9ma0to
        T0xYVzMwWStDOHUzKzRNUHpHTmRwaDh3a0NrClVBVW9rbGFacXRjWDlhNkpaS3Ny
        MmVuNVZQcEN4L2ovYjJONmdYczBDZzAKLS0tIFkxaGhLMlMvc3IxQUtudWhWWUEr
        dGNpMll4Mkxwak9HeWhqeG5sZU1iS0EKO5XHScP1CnXKu+P0h58OrJZeZ8/GZ1CN
        N7LPBKr0DO2n6dC4A7Tgyn5T5yemxFRB4YvJy4mv6IEDR8NrOOUZqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T11:06:42Z"
  mac: ENC[AES256_GCM,data:PGBHShsQfYUS4ey5xzGwZ+yYq3jrBBmdezXccEhAO1tAs+GtX6/Pq+xGTYTF3bi+ACFt6EPA+LgKe1ZwxTgfbT4exRtl+f6kF/Nfg+IvbliwtCPlAfCzlzRCb2eTMjhz1Hfdt2DHM1OAXA0egOkegXcLgErdiuVVDqLo5D3kFgw=,iv:1MzpifPscEQGk9BM85GGven+Pm/gWpYH/daHgC0y6jY=,tag:TuFou0w2ny4PXXcig/CmDA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
