apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:N4GgwRWc2PwjFynAOyz8VeKV8ySvX/om38DMUlw8e+hT9zrLCsJVm9sEANblrfRTO1Fiuj4=,iv:Dn/9Of1tDG30zwPp8siqci2aBD3kRFZYH4xRpe//UsU=,tag:qJEQe3UB6JTaEG6SvRS1Mg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYTNaaENqT3VIUjZxOFpV
        UEVlS1VKaTU2ZU1mcFdrd3pKQzVPczVWVkRJCnpJQ3JWNTMydWV4QnljSmtNV0Ja
        MUQwb2VwWFhHYmhwT2haRVRlcUpKSXMKLS0tIFBkdE14OUEzU2hveVZTeTFHWktG
        VC83R3JkT3g0c0drem12TU5PNFlkWmsKra3qrXB4QmFBmM+6zXYErXE3yL37r/3j
        VlD8KPkFEyqNq3ZewLbYYbM3v0o/mN+htINyRtSzysbYAK4DiJWWjA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T13:27:05Z"
  mac: ENC[AES256_GCM,data:VsfgcWhEiOs/9seKQ0LztSfW3Yg5svfTvsl2rfLJuYRdN+ygh2+Q6CR7bME/m0WQY+a6KVxZK9iMpmDGtriWeXnSAZdcntuJIv3dnCzcPKDD/r6IGOZsx2PVkerWEaAFOmCbTnsPHzbgSwtd/bTOdW003E3jNoPDrskrcOAzoWY=,iv:e7yNJgcwIEMKcoS6BRTf7mff55C49dYLZIZH9kQY5Q8=,tag:+mGKiOqXZTIelFMEyYy1BQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
