apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:C1NmgsCCMlGhNgCf0mgcYPTjA4W4SDByhFbcrc6/Q4Nd30kmk7sjesLmRT2C6Dz1P/NIYnU=,iv:QZjM+KuXuU6KT8Axdz8zpk1Z2tqkybhUSB+Li/vNAfw=,tag:Dz7R5ulTCWJob5qYPuCcJA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESHpicXRQcHA3c2NFM2hP
        dnVPVUZ3alpIZ0lsTkkvQTVQb0N2OUE4c1Y4CnNPOHhHcHpNVUMzSjEwTloxaGQ1
        RFZuVWhNUTFnS0hhWjN2NWUrSy82dUkKLS0tIDF6ZVBHVEQ1akFvelVxOGFjbG04
        dHNpZzh6N1VGR3R1aG9kVnl6OG9FSjAK6vmbkHrp8zX5puUmIyDQsY8fyRRXLffS
        xqp43+hCyCfpGGPIcm6bKiJ5nm+1PpWp+CWBnv507vE2X+h87dFFag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T17:11:19Z"
  mac: ENC[AES256_GCM,data:F7SjsdUv0Hd+ZeqGunTcKsLSqskYXeHxaM4GQyKnCsaGAMQIccfWlV4XqyFmbeUFWZuF934ZguEdyorkzDxro+4wRbx8ZX95sUc6xKXnqXcrj8DBU2Rd5JLCEBnLIQRAf+XYZ+++wHTE6PtlLtHPwzCKqaGQPeFLiUtowfeWKLE=,iv:cMGOJsl8tbbgKbpPZKDl0QCuUm1JBu4FfeSI09o6r98=,tag:zWJ9k0KmF4AD75qaqrps2w==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
