apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:DU5CBSN9qFO9FDuXLs1kdEV3X225q95GIpoZKN5qVY/piwitHK72FP19DUL+ugs4yH0Ew+A=,iv:S/ZcaiH4SWjs8WHzA7lh/gln0Y0/dOuV0LhPIOTwa0I=,tag:IQ7ddKd2YnHUXyCV76e9fg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0b3VQdHA4dlB6Z21Nc3d6
        SFhMQ3c1ZDhicDk2SWdGT2kwU2RTT0F5WHd3CjBLQy9xb05jSEgvY042KzhtQUNX
        STJHT2NzVmNFbnhJZzFaWXZteWpKalEKLS0tIE1FcHZhTUQ4Q0RWNmNaWitLY1JR
        bldFN1Y2MHlDMlllVWJVUS9pT0J4cEkKBZ2RO1z2RY8yHjwUKwgG9kYncXS1PV6b
        pOuPwBoLaR/O+gqDD4DsSr/TLsxZmwMArhqdICvL1Eu9pP01MthSyw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T17:58:47Z"
  mac: ENC[AES256_GCM,data:TLKk6lWDQ+bcxxCJe6CjxHv4iizUOG1ArtqlFp3ngHJPHUxHd5sTqEwyGgSSJx5c2nyuaBumb4Fd5ZRzuLLuFRBjKPayIQ+DRr3ZwLTR0vrksElQAX8AKJeIhBY3e/0UFoLwi0zWA7qj0BFVnXfsjf3sHSOJTEl/7mvQ22PCOrM=,iv:xSEgXPyxbkxvgeiyBbTfAAGm+svKJ5CpTk043jmdEsY=,tag:XsG0YwXx3mT/Eo6GZ8t3yQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
