---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco-operator
  namespace: falco-operator
spec:
  interval: 1h

  chartRef:
    kind: OCIRepository
    name: falco-operator

  install:
    crds: CreateReplace
    remediation:
      retries: -1

  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    replicaCount: 2
    extraArgs: ["--leader-elect=true"]
    revisionHistoryLimit: 5

    image:
      repository: falcosecurity/falco-operator
      pullPolicy: IfNotPresent

    serviceAccount:
      create: true
      automountServiceAccountToken: true

    rbac:
      create: true

    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: null
        memory: 128Mi

    livenessProbe:
      httpGet:
        path: /healthz
        port: health
      initialDelaySeconds: 15
      periodSeconds: 20

    readinessProbe:
      httpGet:
        path: /readyz
        port: health
      initialDelaySeconds: 5
      periodSeconds: 10
