apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: falco-operator
  namespace: falco-operator
spec:
  interval: 1h
  url: oci://ghcr.io/falcosecurity/charts/falco-operator
  ref:
    tag: 0.3.1