apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:3687KZ96fVQ=,iv:fCtWK6rNGe5U4aMWcwmAgi5xn6iuUAQABeJCi29N3/I=,tag:QKtNoXbjLFbT1uDyo4A9nw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YjdsbzVIemEvVDZSS0Ev
        K2dCMWdPM0VQdW0rL3VCR0RxWFBCbFh2cUJJCkQzNHlpWWFFcGZvVTA4SnVXZ0Vm
        Q0w0ZFRjVG1kcWRjVU4rSHBTV1ZCbkUKLS0tIGlTK2g2cVJsV0xxMkx1VUVKaDFW
        TWVNZEtBeGRjWkhoNlNrN3hFdmZKcWcKL6dpi6Y7PFV7cXgg5L7xplJ32Wd+k3ud
        3gIVQ+V7Z03fwdWfOGI2WUOCFG8i5kgrjzwoXHPbXw8gJPGddbM44A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T17:54:31Z"
  mac: ENC[AES256_GCM,data:M5XAbZzeiD9h4TLyVuAC1i6P4HldJfSQqCPSGztrvd64pBisBkgiSGVvnv+qYJMGc34mob68I0uvFx896vO78yw8IlTS9CAgj8diuW1+osqxyrMJX229sL6UYxXoUrMn4poXPMLgcKLRkLv7xxDR6ZsxnRLyjYulESyXf0lI8Qc=,iv:brgL7CSqw1aFY1oacMH1hTHKNwkUu+0Qc1IUllmcCys=,tag:z+EWXOFpHP3XEmuu7lOBag==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
