apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:coliTtbtZUBUdbi5jXBCLw==,iv:2fIFJkmjleQMOWNi2Hcfc3y2B8hPqSZxbpWdJlpkbQQ=,tag:t7fSfLJr/NwmKRKFoDkhnQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeGtjYmROd3FSRDlod0cx
        R2I0OGhRRCtpbnZoZjh1alExMWZUOFc0V1FZCjhzT2tLdnNxTWpub3VLeE9uVXFG
        bk43ZWVjVkFxOUIxcE1XbGtUc1NxbE0KLS0tIHJHSE8rMStOdTlPYmFNcHVMNWNr
        VWJRL2F6ajZLSFRLSHlidUo2cERwbmcKfAf/53lwmPnZE3jnH0vpb9ZiBL/GCPq8
        kOibsgUR5VjMs6vcgD+0Xwbfh9IRcsKpCjS7j+X6QevlWL2AnjqFRw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T21:00:09Z"
  mac: ENC[AES256_GCM,data:+e5QHouoxXo2hx29T1elRleU6Iia1matXAjaqIGt0pC+uwLVxwBp1CNDqQTuPaKOPTLKKGcxrPPgmjywFBb00mf+kMo7SiqQwdkxKyNhVzpqNfUNCfJhKEPu8a+veNxK/6scKI1nqE8Xe2+wdmMH2tNvOcDh8JykdGorgE3LqjA=,iv:AAVLXYGSskGFPdrcIV+efkiwrjVPQnYiPv48YZswwo8=,tag:p6TII/H+xNlIavb/KL7XVQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
