apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:fDCzwgcAfpY=,iv:LCbyDQaCKWN1eEBrHR7sKqtla1MyMz3RbvRKNTbk234=,tag:VY4C8cI+bYOhB3O0TMs0/Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbTdLREV0cEFHMDA0WFhO
        UWJGeTVuSi9UeFpTUWNaMlpNTVc4cXdJSFRBCk5DRnlZYWt1aWZoek5DUjQ3Zjd6
        c2lwODJONmJuNXR6NFJNN0ZmQmxrRkkKLS0tIGVETk5uamcvTVMydmptei8xVDV1
        Ly9UdzlvdmFWdDI2TGMvQno3OFBhVmcKy3/NQFPSTAiNFmDB2AD62lfzSJHclGhp
        PPD0Wh5yrHCkMN6dayXnMB0PGm1fhei1Jb+UbvEBrHw3+3a8YTHiBw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T13:27:05Z"
  mac: ENC[AES256_GCM,data:uzaZDXF9WQOXPXz8NFgvWlKtQkRl8rx3CeK+fPOsndAP6z8uqcL6zyyhhqyL5pWl8zkvBS+hkkEQHNeDM4UCLfI1zY3qeJXNdIgVhc2Dxmir7Zkm8nmWr/8VGIbS9HyMPAtaxw/Lj7AVunoO+dCl49nxwcyG+5drQpjqAZbTQUs=,iv:Rp5mN8DP06B7Mb9yOk2m/QjldNMTWpWLJJ7vC4vWMEQ=,tag:Nb9dkbC25bP55AQ0LjlFrg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
