apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Z34ZgnTQNjCaInEieFh+FYEcCb81XIktJljXH68yy4E=,iv:NRI8Lspz5xjpJsYlE1ECt59skib3wxKLO8Q9W0nOh/0=,tag:+Xd+7Tyt3Z0kzQpDdM9dBw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqY2dvbzNLMCtGRlhHVUJS
        QW5DbDFIdEtuRmYrRXY5VmV5SGFPQU41dFcwClhha3ZoYjBpb1E3aU1xd2NCcjJo
        YmE3cnZRZUltOWtuM3drVU1wQXVKU1EKLS0tIDhUcnBRWjl3YnFnV254c1FuZW9O
        S3ZCQlgyZHJ1UVZyTTFPa0JDaU5uOHcKuCTkeycyTWKNM1d20kO2wTaXFuVgAdC+
        IHcVJI5BFmQl9Gd9V+niKwMsOQ174egDGZ0InjtcBpmr7vSDaILvEQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T17:54:31Z"
  mac: ENC[AES256_GCM,data:esU+Lcta0NhVQ+LlOidHTzyY/uyfzHmngfrz3FivgtfHi1+86pXGo/qDBH6jwJvYjJx8ENY62irD9CEEhM9bnUX+sYsYEkp2v75JFUyKxjWbXLBf9J68HgGu7wtCvcpIUDim7uZS6jApXxi24f0IVm11xEtKjYfiHvVg2lIdlyM=,iv:mHrH1OnXCDEjawL/z2/kBvT8CIiBueBVBEuSRqHYvI4=,tag:r9C8rd1HX7aCuxn+gAC14Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
