apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:l5gcj5DUbeDr1RB2WP4UeY6MNsuo4lJH3ok2Bg4Eby4=,iv:bdTJCq8Aw7mUdy0yZbTiT5bGDDfFOx6iXC605a0Rwl0=,tag:NWAu1RZ3sHO7EI6TQFhbSw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQmFxWCs3dWExVng2UW5P
        bXlhV2FQa21RUnVlaGJZZ0RXQjhBSkNaWWc0ClQyZ2dDMmRENmI3RUFyemljcGJZ
        cnhjWlJVdmQwcyt0RUsrV1NHdzN5dG8KLS0tIHh4NWhhQXlFWjRhNytxUmJTZmZW
        LzQ4K2g5d2hnQ0FzcFNlZ3dnUHNNUGsKBXSae3VR4SRxz3Pz4zNIA/niUMknEC+B
        kTtoCPzMmueJDdDb2SewYZfWJAJLFezyrmv6eMiXGd+4tTsTKL7Iaw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T21:00:09Z"
  mac: ENC[AES256_GCM,data:QH9tCxeJUomfevUkPT/5LhC43hYUHFEW3oNKwYsQiUwNQFKlbc0wyN1gyYoMRtPvLYJsYRfeVgcCbkUjW36CQMdqWh2+w3FgTZ/vqLZQmjMYQrE8mKKom8YiidtRwhKz8q3evzVrCq7r6y/luaCge/rPQ7M6puhMZIOEVYJO7c4=,iv:worfFmj7BkJQ/bfnyd+alD2NSac2nvta0IiDI397/Dk=,tag:KcQyrwIbfYy6QwdD+sxZVg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
