apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:KJRKZmVD6igOlf/72S0QBrtFWGA//mmPuWRnhk3/Wo0=,iv:DI3f0fzNYDFGl163z7auS1hfbs5wsQpjW0IPS/ldkMc=,tag:4+tPyXEeFVSzC4ruOeqsWA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QXlKNVhsQmt3MkM5NmRr
        QzlRWDBqMXBWT3FLa1Z1WW5SN1JFc05ZL2xFCm9XajhuMWtjS29pcmsvZGZhZm1n
        ZmdyaUJjUjVMeEgreFJ5SzJwZ0pKcGsKLS0tIEg1Q2FJcm9odkxUOGZuK3djL25C
        MkpRajVzWUZiVmR0SEVUYS84aEhvMmcKRxS+Vi8YuQdrj0GMcg74SWdESsAAlb+m
        P1zL/Qe/f/8qmgQfQ2bgH1DJ/xT4mBx4+7qOlu1BHQjJu0fy57ce6Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T13:27:05Z"
  mac: ENC[AES256_GCM,data:Sn0lb6v2u/OvDFEBZN8Qh3XX5d7B1no+BnI2gFCeQwnYVMTCVCVB8LdcLGgwzfr/mrs7oR7h3uqvUuhX67CI0GMYqn+cRDOP/eA2X/L20Rt5q/hOmG/rxDHwqE7JjJAeWgRAw4/vSgHv1MsOs+JKJduLssSMVUaW4mG6PjOz1fs=,iv:e+owyFKrKMb7wUmjuf0Dz8kjI7wjXfJ6gJwEyv6L2MQ=,tag:tHzfUKhapOrtlG9yCscIjg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
