---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: travel

resources:
  - ./travel-trek-allow-eg-to-coredns.yaml
  - ./travel-trek-allow-ig-from-envoy-gateway.yaml
  - ./travel-trek-allow-eg-to-envoy-gateway.yaml
  - ./travel-trek-allow-eg-to-world.yaml