apiVersion: v1
kind: Secret
metadata:
  name: authentik-grafana-oidc
  namespace: observability
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:72+Fic0qePoUii4SiewCkn2ku5vQCnelMvfYgPE9PXQZGek3BobEN8EARGOL5B+mstSY0Q+uT9iS6hp5nF8llw==,iv:EvofziGSJFa8IvP/X0h/TE5f7w9KnSGhUglkE0CRFRA=,tag:jAPab3h5SSJxbDT0F3/vNA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZjFqRHZmWWdhcEZOVHVt
        eDZ3b1JuZkpXcTFPejRrNTRScHRHQUxSL0dnClpCd0ExYWFKUjRCKzRXcnV0akdJ
        VHA0SUpmMjNmVVd1a2YwSUFMMkVQK28KLS0tICtJN2ZuUmJ6SmZoWTFkQWlFaFFW
        bjZodXorRDFpUEE4RjZWcFIvMG9CSDAKs27wcqAGkGEOCT4eujVR99HjpqXKM6PC
        ren70NJGs6o++zMhfs54YGkvCDYQvtEud69n/J0ls6QV+inmvOZ7kg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T13:12:22Z"
  mac: ENC[AES256_GCM,data:qLu/wB+/BDHDfLraucDVjzFw8+Csh3nKIpewTAyIn+mz6NYnq/QozS1GTQr9eTlPpKpm8euIrA3XI3ovayEbhOWOZ/cgufWYgVgmAHNZ1PjY+vldwNC3c870YziRIlBJTyvznae5XblFNSnluNtQg4qvCGEcssBlkOUzjL+oVhk=,iv:GrkzoUb5isoikc9jks7xRZHSVdS+WCzs7eIwoLJTHfA=,tag:FrMIkXDsCHmoh4CppBPcMQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
