apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:YgLAQtOyACW6v3cDuNkFq1ZdP4o=,iv:HNV1kPveK+JJbRJE5GQvLdjftL2wswMO4nsXolsILrw=,tag:eLAyIWf1rq8QOeQMGxV1AA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVU9xU3h0U1U4QnJqWHBF
        VytNakdvVGlvVXdUQ3ArWEQ2VlpHKzVrdDJvCk5XT0xaeDlxMHA4UVRrdVoyZnd1
        bUtZQU5waFd5R0I1bnZGQXppajVRWDQKLS0tIFJSejZSM1JteXdSRGU0dVNQL1ZC
        bFc4U1ZCU003UmNKUmxiVGdxQXBnWVkKhsU4C3GqpgV0m5CunhREBmg6nrbQBYmO
        dfGcZYhNf7mEYk/MRpMZoGI/VGM27ui+qitkw/UDJUioGJL7Rb/tUA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-07T19:01:25Z"
  mac: ENC[AES256_GCM,data:hQ8eDX9X3aI/DEXajMBsY2fRZoK0cyGCPcAHgqYafqTMXq/4vKoYEXsaslBKZ2R4yTCEa0mBdsxTuk0uGcFN1Xchxxll+bmn7Jigxui5To7ZrVhyFLni0dxlWv+9alR+d3dJuRIhdCggulMqKSFB1JSKlzPyClXOSops4k9qFcU=,iv:tzQiuaqmdn99rm4Q/0unmQIcOF5OGBARmdG/XjNKCDk=,tag:evK+rUUjtaotCjwBuvoeHQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
