apiVersion: v1
kind: Secret
metadata:
  name: authentik-longhorn-oidc
  namespace: longhorn-system
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:Pu8XnN5op7wMIaMRg42b8HE27X135ECOQi0wbFxxP4+3JI4jZrUVVsuq/5tlU5d2LRYSdE4WqdCIkEx67HtQyQ==,iv:WEa0GuTTfLCyaoQFS8n5sfdw4jMBebTTBxVM18JYQ7Q=,tag:ty7+6wFCre2rRH/W5fUXhQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Q1BhRjVoVGNISTcvblJC
        SklGVVU5aysva2VuL1gvUmszS0dkc3JkcXpNClliZ3B5QWY3RkdNd1pEMzJxWnIw
        RTdIY1BpV0F6akdpMk9xMW9zMXdVL1kKLS0tIG1TYUFWb0ZuankxY2FMdUYxdlRs
        ZlpGYVU0QUVNdW5BaS9xSHFPVHpSZGMKcFY+EiCLbDmdcqns2PgUbZbDRJQLIXvQ
        1iwb+pICdSPeTtCRg8Gil8HFPWX2SnCFaIu90ntR4zHbkXxxZDbnHw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-21T12:54:23Z"
  mac: ENC[AES256_GCM,data:hBvmr8JuRctFRi8Euhs8bGEtzFrACpgynW1HiAoQnwcBzr3EA85P4W9bpqG0A76/DWnKlx2bj6/6mw55sMVNSCr7FB0Qal7AXBDr3B6IShGjaHzQoCb1NQ+uDVah9oJh56MKmDYXyJIeC8EYVznSj0a1TovWE0FBEJNVclFU7nM=,iv:s47aisFhBGtEMgeb2TbU6GlNj+70Dzzg4N6IEnMEnoE=,tag:hVkkhze9gG+0D8JcaXoFJA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
