---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-longhorn-oidc
  namespace: longhorn-system
type: Opaque
stringData:
  client-secret: Uq1FqKQEdK0JcRCOMQIggGIH4cRvwRi6Gl6yCmDpkuGo5hEBsvReJzK6HLpSw3se