apiVersion: v1
kind: Secret
metadata:
  name: longhorn-s3-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:7T8U45tj6ivG5ZNiQNzt5+KTcE8xLeABQA==,iv:9lTN6EEUq2qQSAKVXYV8id3EhQMTm+KxEcWHBxO1KXY=,tag:vFDAxFHMaNWxBvL0KUBe+Q==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:zGmrkKfzarK/3N+dQAlYg4/v6juQNTLm4P2//s3BEv5lLUC6YWJwIFM=,iv:qNwvIyG/6uVelv/XQ3ZKAj5HPyZ4nUARBI6ZWSC5sKg=,tag:kRx5X1pIIU117UPh3r5JrQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9XDlnRp0go36evCjNuUUeDUD7XNw3OEprlUQIps6Lg==,iv:URwrw2xQRwFAB1YtCTCrzSkatCoRklO6lL/4z5hNevc=,tag:0GC+NWHaYAzQwG0/eWShHA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RFJBQUdydVRZVklkS2R2
        WnhlcUZ5MVhVSHBlRWdicnY3eEwrTURZREZzCjB6dU4xSUJtdS9ONVJYZlpOSzNV
        UCtXQUVBM2hhUjFBRkNUdktmalJSbmsKLS0tIEFRZXV5eTc4YmlaTTMvbTJBeS8y
        emo0QzdPM2FmdGlQMnYzM2k0R09PWTQKpbsn89GKec1U+svA1bPW4KLV5A1HCWEL
        f2j4ViNx0okjgoXFHuWSXShDKvNc3A88F+ZQD/lWAkSqBB9ogx1ArA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-05T20:26:14Z"
  mac: ENC[AES256_GCM,data:ULAwMzq82IDf4mv1bJE6nyITbnbkyH8g5gcWeSXfq33JjI5AXA5m8Z/YkoK1YiRgtY4r9aBIvX/V8WTCr7tHw1JsW5p/ON0j9IZxzNsjsCVV428yozB1WKROlMoaZ3GMc2wUsXe3/vulBOYQkq5cXWfLAVLUSn7RgYKhsrBKxqk=,iv:qKyo+z0PTqn9XPoCQnHIEwdvmF3BNgU3kV1fwwOMV2s=,tag:xf85M1IRXphOTK5m2+ykPQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
