---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-no-backup
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-snapshot-short
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  recurringJobSelector: '[{"name":"snapshot-short","isGroup":true}]'

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-app-daily
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  recurringJobSelector: '[{"name":"app-daily","isGroup":true}]'

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-critical
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  recurringJobSelector: '[{"name":"critical","isGroup":true}]'

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-db
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-db-snapshot-short
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  recurringJobSelector: '[{"name":"db-snapshot-short","isGroup":true}]'

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-db-dr-weekly
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  recurringJobSelector: '[{"name":"db-dr-weekly","isGroup":true}]'