apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:8yFaI/PMmRDjJYgexEx9arCK7tuRA9hYnPIV6+5bIRgG3DBZTk5C1JKz749Ch4AmXdRilL1FmwaJakw5d+FwzQuVzmpoY1e9kP5XE8nDnzALdkBAWK3yXwhuf6/1AaB16bveF1K24Z4buqVb7ZB7hsCCncs2Cqpu5JEy2k2NyU1MKB4+B7n9+Dlqh9jWkkMK7W9nSMdjdI8MW3tQkwa3Zzua1X9jm8Xxgv2P29tSOKYeI6oR,iv:z9AcHfVFLFBBItcXPuN7b6q/0j6KXkvLpB333HVqt1s=,tag:z4lMQyKCDCCAuVpbY2Lm5w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eVJZWHY2K2Z3MmZBL1I1
        Z0VWdFZQNlZWQjA1ODZBMFZvMHh0dWc1bXlVCmVXZzhZV2RidW1HQ1o3cmN6eElD
        ci9XcVpLSmdSa25Remw3dFZmSkVyVmsKLS0tIGUyYTdpZHpvSHBEajhEV3F1bjRI
        bEVSYkkzTW1xWTNKL3JleGU4T2xKTWsKHqLzOOSH7tPdU8YV6BtRawFTHzS2M3n+
        HGTF1Om0Y+nqe1CfViiKUF/3Qn8exD5meG64xqDJkqwHjfqo05AfiA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T17:38:56Z"
  mac: ENC[AES256_GCM,data:1ViDx2tkdRFbWgEr9oY32ga8hKXBk05Hc5QJFEZZ/TgX1x+IHHKKg84S3zU+yCo+veT4hX6MiD/dil9NOWaJKK0TIR9c2RtDvsGE47kAO5wu2eEubYScW0gXS0pq7AaAb8Qo//eNM2F9WALn//3GZDecZLqFeNunUxbbnuE1WOU=,iv:z7bgcNOly+ElaJSfUErCmU25y8wX3kzIS+XdXTC32co=,tag:xK/b7JD0yRnm07/Szwv6uQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
