apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:RZ/Y1yuioKd7dnQ/zBCt0X79iT7p9jpL+IHer0Rw+D/8vKsGRg3Hzezfv1/v+UdNfNYbPm2XXcTWhq9R3AqfiiAyhGJduCgAbo8LM1o+1fmRNH2bwtsntGuY0zjJuvijmLAtCJATMDX41bFu3Y9RNdog4hF8xRa69SQhdiKepHnb5oe5yx1rmO6lMJpuRT+3EsCDWRY7yevfM7JrRObQ2/Z2OcDBvWA45nLNf9wMn+Xp/0Lh,iv:CTaiRZiZJFmsZrLRvT6xLl9caeypgzVw/XAtffFFYtI=,tag:Hs9t84UOlzEZYFnfdQaITg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaWtTY0ZNbldOL2lOSGlR
        bXNGcGVEZldPSmRYUCs0TkRTOWh4U0p5NmxNCnNwTDQrQnpuRWtvVlh2SW54NTR1
        N0lKK0UxRzVjMW5WWUduRUJiYmJ4QVkKLS0tIFdXcFp4YWdLdFEzNXlOekQxS2dY
        eTJNc3pNZms1TkxvNUd6R2FnT1pCODAKWgKO+4/Zh13/KLN+58zcJPEhKjWXxVeH
        4xFLYeIqNrkNB5njm35NJa54JxRZoqtmjSwo9V3R1cqgEHSsy5WxxQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-02T21:00:09Z"
  mac: ENC[AES256_GCM,data:/SvcK6zoTv+qLTvV1GdoZXqsIIkktC9rQfgjYXpHgwdJirkoBgZCviCDEhWSSzYMYOpBUJRMHmkyANVrRpDV3Kmv6eSmgVE5EJYPEmLFDUcplRIpD2oGX25tsNcXBYrrc/B4KLSk/WXRmUejwpUlRyznar9IN/K3O6yZLdnoDVg=,iv:FNm/khyBkNTDuLpATkLGg8ZFf6FOhHXUdEMbdfq20b0=,tag:cByLDyq54S1MY88mKL2VoQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
