apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:e+dW+9aJ8pxx3K7oHbkhkS43lwioimZCtiXFTdbeJNZhnoyFGIa1BniTu0wo/Ayk1gdemgXocRO29FyNjTOUA9LGie69u83V+TxWONHZavtnUYvug1tIzjiv9/RvoWn0xpxAU6C+xtMbfi3WypHL4KCICfQjJl55TGP5RwLlRLFvSuFmO4tQsiHTtn57okZvEa0YJN+rwtsyR1ooBMSY/pMUwBXBOaeOAN1uk4QGjHPvIrBa,iv:e33yAWPrZQhXl3m348naC6vPtD99O/0cHozK+p9O2CQ=,tag:s1NVQ4iQckm5I8rWx3qBJw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUFNzZ1ErRE52MkMyN2dU
        bnJlR09aejBHakV6OEdIdVBQUHFmeWhZUXdVCmQxRmcxL0dSQjh3eVdqVzZGMmRI
        ejl1WHpWdjgrOEhISGhHdHNjTEJFb1EKLS0tIGM1WDZVYUlFUi9hVXhWaHh5aFVi
        WG0ya3VpOTBzNTY4dGdiYkVmRlR2LzgKkruEc4y9f/piyTodQfb/p2kCvHIIPUo1
        Ax7P1mJOSZi95eXQ/cP5pjlzruYYjEplHLMzdBOTz6v4agS+O9hwEg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-29T13:27:05Z"
  mac: ENC[AES256_GCM,data:h+5GTxI76utdIP8KbCuoCDLFmX37pVeYgUQUu0H0SCbmWnou2xgRqjeyHufIx+CQTPCeEAiVOQYat8vK4IpH6yKcCux9+yD3CVtDBGV/zqOD1ctM7bWLbEV3jKkBNVL+7ZxcFbqtERGjiUeHYWUSNyBydHPNKrqf4ckMKN+QfUM=,iv:SNYo8JfyGdXvJIyhQ0cpQEU5DSKovo3IeTod+6XeZrg=,tag:hoS8vftJ40DiJipFFZNmJQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
