apiVersion: v1
kind: Secret
metadata:
  name: authentik-victorialogs-oidc
  namespace: observability
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:GiDTA9glD6T6LurZUfbrIAg27IxB5uhMBJDwVh/rMOmS66Xeia982sAJOieYjbNJKaZtmVchqUgjpP0lMJJTgg==,iv:IEW0ZowFWRLh+PomksK9/rKVGnikvIYVIoqV9H0vk+c=,tag:7tcqf3BiFFneStOD5xNTFg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWWJON2xVd013aXhneUlZ
        Nmc0Um9GdVFldVlJbkc4eEkxaGtsMkVSSlFnCncxbndrRHlwWXh4WGxVM0VnNG16
        RktndS9UVi9ob0tQVVYvb1FKYnJxZGMKLS0tIDRDQjU4TmlnT0tzZ2ppaDhxOXZ0
        WUtIVzlwOXUrNmhodXB4ZjY3bEJpREUKBaAFz0E0YhJ6AJcg/FD/SnrWO4M2pYRl
        AHcOE8Lcd1zV8r7VRGys3RZA5P7UtMWzHZPMGTNp7pUoONGtZ9v1Aw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-22T10:47:28Z"
  mac: ENC[AES256_GCM,data:qoF8A8WNTD66TXg/a3vSVxQLL9PYg4ige0Ql9f+j4H0uQFj1CY8mOYBXwmMFCMnVKnCILQvkDoaIPi0UGHu7Wlgd/9UXi80wcYP7cbNJRF0RKali04YZ+bJZDXn35asUcXddAqm7VaqOUccadbgsmYycjZH1RA69szUj/qUIK2s=,iv:hAcP8GFzc8zEQI23kuZ0IE3gurosCQAwVqM+AxSlG9M=,tag:xvgY2GQZpMXZD+4JNAa5uQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
