apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:JhhcQsdIlVaz7k9E3ikPKV2RaO7W9Yt6OOfQMXWfCnwECX9+9IX9i0Pwt4TXwUXv9Z0Hgeo=,iv:c1P1BpLOIhA+rMm+G3v0fkTJcCk9fuArPHM9KE5/Zsg=,tag:0ca7VI7aKHL4TgxGyPz27w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWXB6VFpNRmxrSEpjN004
        MHFzVTNSb0FLVUg5dE15R0tqVjNzQ2laaWdFCjdyL3h1d0RGd3Y3TFltek5IUzZF
        THh6T0dNZ2oxeDBtNWJxdmJvTzA2OVUKLS0tIEhMd3dYSVluV1FkU2M1RHlzYStG
        SFNvTUFMMjlRSXVORUo3YzJrVnozc0UKfBhS91DdLVcJHWhBVY1rof4UPa+pmGLx
        Y77a52bBtEjhk5PBtXPq7WKi0QtejqvQEGqZKrJzXlQKAmlJXOUPIA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T17:58:47Z"
  mac: ENC[AES256_GCM,data:08+PbJAzTZGszJQp0bjqv6C0lns+YpZooRoz2r8dPMSEFiRsYFVlapiDPATMxpw4qe80eQdjQyfGtFPdYGa0fEtvqY8w1aQFpqbJI2N5COE8gfBVZacnM4J5iVvxukwRZlsFtYrbLNEsjwSDnvJDvLeUhObTX6JJdtU3B0G5hgw=,iv:uGZexreh2rtGeyD8qMvoPoefgrMxdUcBOHzEjUZTICQ=,tag:w1HVneL7RFyvTRm/0x9UoA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
