apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:pTxZp4F3TQ7l5Zcb6K8wGgmBK/U7uqDr6IgNXikUCDqI+9AgkuJ7tpbQMmowKgZz4BFEPoE=,iv:nQjIjCtL3KIHtWWtSA5dnLz6r5HWjjdlKK9NKmJH4RM=,tag:0AWQxwcaJKutrx40G0dFdQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aG9XSGtUVVMxdjNQVVZl
        SEE0cUJaL1p5MGVPMk5WR0hXVTU3OW5xTEFvCmZQdzlyN1FJZTc2R2ZoSnU2QmpS
        MzlydmhZZjZiT2x0ZnhtKzNIUzJleFEKLS0tIE0xbXpYRkpQdlA5WkI4dmxPelVN
        dzVQUkVWbll1cE50d0taaVNqR2padVEKTtkhlEvskIePgQY4jmPbAKy76mNtozQu
        u5+fr/6PalG6oCXzVhVsSLM++qjpjioX2LYcvgvG6VXwYVtevMrbzg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T17:54:31Z"
  mac: ENC[AES256_GCM,data:qIv9BG2Y1bcr9jEub9+TuRl7bdOlI5NEYKuxCaUiZe0hVq4o3/eVibyeBKrMusWK0XFuAhliEkT9CLFElf+OY/ibwG+gfbEOw3APpYadx022X0HgPzQZZQKsyA5WdDO3SqCNSsHvuTHCHRKPwpGeX0cupSOkTmVG+X3bmeDFHK0=,iv:kH82TbGAsGVMQ1V9wImp57qTRfq3jDvTiiT9HEuE7wA=,tag:bSzf8Ldmv+DbJYhwj/8hNw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
