apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:5jh650yleD/AN5dbLF03uYXjMX29NPofpA5X9wUs4vxT6wnXUUxFRW5GK2GHw/dE0EmaaLY=,iv:HZnRH9/8Js/IR8lZsvE3OUeUzy3kGdgV/CEdopkqVGM=,tag:tNKZ3UZViPZIUYYKF8158Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4M3o3WlJodUR1RWJBVWwv
        SUpxaXNvZm1BZk10bmJyMGNZRXM0RW4rc3pvCmRvU3FvSXlSQmJIVTBMclNTelNo
        bG1xby80bS9UdG1wb0MxN0FYU3d6SVUKLS0tIGpjblIvOG4rby9wUExURlBUcnBY
        U3daMjJCZVdSMjlTR1I5UmpjTkJFR3MKrAXaDCqzhk0uSYjXQLSS5VmdgwydZk72
        RDzBN9OSoFRbr7hEFXqE5hhpDWwcmmaQU1h3q4xHlJvBy053On+96w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-01T17:38:56Z"
  mac: ENC[AES256_GCM,data:23/BihbatScsGwI0RmLxmk4g0gRwn1iwJz8KIb3O9z5PmF5KbgF1lyp11vcV4y+LJ/HqC22R13A97gd/Aq2PPzk3awOm3gfDeREcUWA4tm8j+txkgoNO42pMvfZPBRywcjejp/j8nX9Kl0sZFyUBsmNQAw2hQJ8zMGcSZzMIz94=,iv:rC2FNVwxWC43uoJ/DFUuxTbUIkGTJqkFfdecSDnqecE=,tag:yXFjAYxZjtVd1dV4JVv8OQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
