---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.50.247:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.50.247"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "ho-prod-cp-01"
    ipAddress: "192.168.50.170"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:9a:c8:33"
        dhcp: false
        addresses:
          - "192.168.50.170/24"
        routes:
          - gateway: "192.168.50.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.50.247"
    patches:
      - # Encrypt system disk with TPM
        |-
        machine:
          systemDiskEncryption:
            state:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
            ephemeral:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
  - hostname: "ho-prod-cp-02"
    ipAddress: "192.168.50.171"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:aa:20:62"
        dhcp: false
        addresses:
          - "192.168.50.171/24"
        routes:
          - gateway: "192.168.50.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.50.247"
    patches:
      - # Encrypt system disk with TPM
        |-
        machine:
          systemDiskEncryption:
            state:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
            ephemeral:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
  - hostname: "ho-prod-cp-03"
    ipAddress: "192.168.50.172"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:d4:54:68"
        dhcp: false
        addresses:
          - "192.168.50.172/24"
        routes:
          - gateway: "192.168.50.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.50.247"
    patches:
      - # Encrypt system disk with TPM
        |-
        machine:
          systemDiskEncryption:
            state:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
            ephemeral:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
  - hostname: "ho-prod-wk-01"
    ipAddress: "192.168.50.175"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:62:49:2b"
        dhcp: false
        addresses:
          - "192.168.50.175/24"
        routes:
          - gateway: "192.168.50.1"
            network: 0.0.0.0/0
        mtu: 1500
    patches:
      - # Encrypt system disk with TPM
        |-
        machine:
          systemDiskEncryption:
            state:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
            ephemeral:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
  - hostname: "ho-prod-wk-02"
    ipAddress: "192.168.50.176"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:bb:1d:3b"
        dhcp: false
        addresses:
          - "192.168.50.176/24"
        routes:
          - gateway: "192.168.50.1"
            network: 0.0.0.0/0
        mtu: 1500
    patches:
      - # Encrypt system disk with TPM
        |-
        machine:
          systemDiskEncryption:
            state:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
            ephemeral:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
  - hostname: "ho-prod-wk-03"
    ipAddress: "192.168.50.177"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:2a:36:3c"
        dhcp: false
        addresses:
          - "192.168.50.177/24"
        routes:
          - gateway: "192.168.50.1"
            network: 0.0.0.0/0
        mtu: 1500
    patches:
      - # Encrypt system disk with TPM
        |-
        machine:
          systemDiskEncryption:
            state:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}
            ephemeral:
              provider: luks2
              keys:
                - slot: 0
                  tpm: {}

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

