apiVersion: v1
kind: Secret
metadata:
  name: authentik-policy-reporter-oidc
  namespace: kyverno
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:bGDfukQB102TkKuC/rTe01mVY1Ifw8yob/qMBwrFzNrn0PVg1rqDHKCwa0sutgBTsXAJCJXWPtSeZ8UIFU5u4Q==,iv:M0qcftXou7krF1r8OBbn5Yo+JkgAx+tUpCT0Qs2/c3U=,tag:uQ9nrbYq+QTca7vKPFBC1g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENDFxeFZUVGZ5SVNHaTVn
        aTVIM0pIdVd5akxCMXFXWFZ1ZHRaWFNza1NNCnV1Mjh4M1c1NTVNSjA3T05LODhZ
        bjR4RFhuVzRMMUZsNVpoYlJ4dU5UOVEKLS0tIG5DcTV6MitEcjQ4cG9xaWFDbDZF
        S2tBV20ybVQ0a05iWFpCNnNzT09lVmMKDl6GezFLCXem/DFs47Q+EvO7jaNS2yEG
        SrOihDGpJ/Xbic6YVJOHErul+w2x9A7hFoytwQyh3f/5YwaxAQqqjw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-21T20:50:46Z"
  mac: ENC[AES256_GCM,data:FCJMO5MBWHl5J5yFOI+KdIBmj8owzBH3rO9DxdQgnLDBg6ZbuANeHJkZKFPMtDefzBFXBzVLKDCGngvPncuAf3TJ597pX8ZMM6iYFgQ43Nmxysg2DcHROL7FeucisN4Zbzip9U9Shr30qpCjWdxU/lGIwM/sEH1W/wOU3OgPJUc=,iv:KSOVcYzmRNBK7vzE78yvxIzcmXcW2J112U2tI1djCeU=,tag:9S4aYfqaXRScNRBCfatGig==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
