apiVersion: v1
kind: Secret
metadata:
  name: pg-policy-reporter-db-credentials
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:jwuaNsIqbznLARFm3HfBqxL6,iv:BzqiDoKj1I7SPSaJW+uvZkCkrN3h5J9noxrUSV2TlAA=,tag:k4xOyDGf0vBPDHTKrbCiVQ==,type:str]
  password: ENC[AES256_GCM,data:OVEifcUV1M8yY/N6gp4NWIHGB//Ms7EsQBho+DsqeDIuRW9e51niZ8bAJglNrke8P0xT3WF+AnmTxZit3PgSdQ==,iv:84Yh0PRjG6oR7zwwu4rRmZ89fOCsrp3WQkOY0TEjW24=,tag:+7iprKk9uD6/JBJvdvlR5Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmd1BWVm1nTkNhcndDOFpn
        Mk5mNmdlRFVjRVJjMmtsTjBLdVY5YWxLQ2dNClZVeStTcVd6aTFLZStrN29pVUJV
        cEdBTytDYUV3YnBDRUdBRWFhVTJTVnMKLS0tIGlZRGU1YkdYUUFaY0czK3ZmWDJ1
        M3RaeG1uZGhSekxnUCtmQ3E1bE95MTQKLYP3xmqj4eLqWN9/A0BEiZXk8ItZT/F3
        gV320ctP4k4jqIc/PDYMYnvjzl8EZozGu6aeK+ox1Y14Nj2yUdZE0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-07T19:43:15Z"
  mac: ENC[AES256_GCM,data:TvC5wQp+yYF3SwJbz5XFx3ZhXaMip4Vi9PNEhET61q+u+qz3Wtdc8jTm47+sgJEnoO5pTJY1BYlJWIgCAl1ulu4O3uVd7ZAx/Gfy4VpZWch9P8sJDWXHr1Wf70GQ2GORJuB44CoT2zUOFlWJMIDLHJgEO8dQWezCi43be6NwvpA=,iv:g6OwCCiL/kk+FqgBfVvnfnYnaJNmE55UN01MIvB3Ygk=,tag:Dsjbc+2yqeFy5k3xExmrmQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
