apiVersion: v1
kind: Secret
metadata:
  name: pg-policy-reporter-db-credentials
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:v1uv89Y=,iv:N1NKvORkNcGlXosmCsyf09ewzzyoO4ySmckNQA0mTC0=,tag:sorwDjKzX8Ugcpgcodp7DA==,type:str]
  password: ENC[AES256_GCM,data:lN4okWGai9hWTOYxGfEX,iv:JgkzgWPi/C6gym1H2Sl5Kwt3J5mMZCsZx6sdQFHym1Q=,tag:N4mlhwUEhTDtCjhxcsuEPw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmd1BWVm1nTkNhcndDOFpn
        Mk5mNmdlRFVjRVJjMmtsTjBLdVY5YWxLQ2dNClZVeStTcVd6aTFLZStrN29pVUJV
        cEdBTytDYUV3YnBDRUdBRWFhVTJTVnMKLS0tIGlZRGU1YkdYUUFaY0czK3ZmWDJ1
        M3RaeG1uZGhSekxnUCtmQ3E1bE95MTQKLYP3xmqj4eLqWN9/A0BEiZXk8ItZT/F3
        gV320ctP4k4jqIc/PDYMYnvjzl8EZozGu6aeK+ox1Y14Nj2yUdZE0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-07T18:06:03Z"
  mac: ENC[AES256_GCM,data:EG/5o8//9kwXI4/Ovv+N3QYYIe0te2Yx9qb/9v8rI2mehjg7rfbKhUUi59FUZkK6delOnPDkxX5wwBt/5XnYQIvbVPBxWhARw0yqTBNnPH3uYfOJq8eeocjInP9OCe1YCd+r+q3eL+wRdrPKV5eLXLJwn2l8XcWpDdhr58d3qoA=,iv:v3/U0yN7qF85uTOZYmHanbYSDTZm2ZtJn8SETcIWrug=,tag:5QZJHqvh3CX4Hy9lQ4rJpw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
