apiVersion: v1
kind: Secret
metadata:
  name: pg-authentik
  namespace: database
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:buxJN0pckfKKOEXe,iv:ZVZNQwfTuF8dlaRHkTeaxU85B+5CHDeRG27LHHdDlF0=,tag:ICIQO1A/Pbe6HYG8SUmssA==,type:str]
  password: ENC[AES256_GCM,data:EBYXDKPviaksiktMByB5KzN3py66RPmt8d0UWjTQcmJ/u3KnaBESun/DQ8kklM9Kzr39RmY7Gn8f2nExwsK3aw==,iv:hR+vcGZhv2KySpeGYJm8G2CDbJGT0RSZrHOj9saphRQ=,tag:zd6VfR9oRu8ybqeviB7bww==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UjYxZ0hFR0JFd2dVT2l1
        Z3JpLzk5SzlqaVNySDZHT3RGL28rZ2JkVlRBCkY2NGV4WWppZjYvOGp1UTNDamtN
        RHVlS3BmVlZNZnBCRXM0RTVQNElVTk0KLS0tIDJuczlWSTRPNE1Gb1Fwd1J2ZUxB
        dXY4YnR6NUJqNnpTUElGcDRZZklmT0kKr7+q4LZ4ap2Fi8xpri/5umF5E5Sp8EI4
        xr7PTpfYxIP+DmY9leHgRLkcWX1u1JUGhuHrwmiPtFXsGYlaJ8Uwpw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-09T20:37:56Z"
  mac: ENC[AES256_GCM,data:BtBM4xxusZOpkJr8r8oGzCSHjD6DUsr0FW8CCx07mPjzFQ3UHJ9XwS2m9EHDtGZhlqWzHp0vjIlPEz1gS6/lzDA4wckepJJcB+mw3xe6feb6YH7ItBm3bZwhjhTgY0imPZMMGC2Icctl18yQPZnYXJsM/TBBt4jCTGmVC2pzjjw=,iv:pPz6D9khqUOHpKVrIRzupEvJfTvpNEv928a5SOMQfgY=,tag:SJjV6wmvIehAB+NqJZ0QBA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
