apiVersion: v1
kind: Secret
metadata:
  name: pg-authentik-s3-secret
  namespace: database
type: Opaque
stringData:
  aws-access-key-id: ENC[AES256_GCM,data:ILXgPpJTUpm41Twc7D/aaZopeLzBdzOHyw==,iv:xQj7oFzPqNbQKCRVt+MgX0jqq5VR2ri652+29kaZ3fo=,tag:vqTigJWP6GUNlVbWLXZEKQ==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:WsbkrsAXMnOqZsHETnz3psznS2lF6YBMrrL3eMUNjA==,iv:S8vDjnJ0Et4OqR99Gqza+28f4sjZ8d8mYyyqv8iTZCE=,tag:nv9in+gZA2MpUBYsjMSi7A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcmxwZ1Q3WmRZWGt0VmY0
        YUU3clFmdzAraGlrZHRmNWFYWHE3UUNEMDFvCmlPN1E2bTdTdGtuOVo3UWhnSUtM
        bGlXeG9pbUlQSHB6RDN3elBkU3NSOHcKLS0tIHhMQy81MTNvNVA4d21hN05xV3NR
        Q2R5ekNaV2JORWRGQzM0N0hoRzY1STQKacXCtxjUgm6vRpPA8NOgLpxhaHZ8jFRq
        g++sl04wIldfBJxrX575Hl2gfTrb8GeqHrDqfw1syU2KkVpFb2YDjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-09T20:34:05Z"
  mac: ENC[AES256_GCM,data:rFtwlrV8LplnKvnRrtvMlQS7fXm25BGpIzbQWc21GcKINwfouLCa38Ke6sglI8hJTe4EJZL8PaKMjvTMKKzs79WhxRp7HAc79Nkwe89/l+vTNVBL6yqusKXTfv2fLKZUbywfl6fzC7y9sA62b5+RC0wjMK8p6TaHuvIMJ0cHRmU=,iv:nZcgaW3R9D+roKYOAHtqC70c7EBxxTvxTP/Km2t0w1Q=,tag:xKFr+VIUJSy3nCac+YS5Eg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
