apiVersion: v1
kind: Secret
metadata:
  name: authentik-email-password
  namespace: auth
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:VS+IOGAsTa4pE74ts+f9QrNAxFc=,iv:gmwzSARIvU75KCSYvWfbHrPIM/YAskqF/NZeE6DK8HA=,tag:CnyDfMgul1kpMMu8+6diIw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTEx0WHJyY0l5dGo4NVV2
        akJ2WVMwbDZ2aUNnOTFiY3l2RmswWkRzOERNCnpEWGhBNUVHblJzbWpQMFVNVEhP
        TUY0M1VVZDMweWZJMXBJU0p4YS9FZEEKLS0tIHMrT2l3cjF1b1RNdzBaam1xWDdH
        eE84ZkRKWlpZak53eEtyTklWaUVGQ0EKKCQswXS5FGMD4hygEm1IgYxz0JoOYZbw
        Praif2XGjFKSJXoZrmL0Ok1irpIy7EQC7yomel5uICoRKBkeUN4gpQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-14T21:03:00Z"
  mac: ENC[AES256_GCM,data:PD0CXG0bC/Rf5mJdZHz9DiHTBBw6GdR0zqIkDb2FoOH2dkfzUbe4rDkNyxFSeZ8YKcfMRBwUpIepTdn/FcTZBFSk+lVq1zSs6pFTLjYoNK/8+BOubHyZK4Zw23lv5/UJSQxUTONqTzWRr/BMsoP5shKtXbj9kd4grDk5cUl2OxU=,iv:UD0Du+aR+zAzd4EiKwxPCf0b7by9F8kledHNR82kmJ4=,tag:qA20C4Hk5InEh9Yupf4qGA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
