apiVersion: v1
kind: Secret
metadata:
  name: pg-authentik
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:4ZKOk3+fNYjSA7qb,iv:wxz2PiZAjb2sDPt80SHe+NrMLTNJAR2IitbV8qWvSFQ=,tag:c/7fBDAZBJFDbVUBLpMXXA==,type:str]
  password: ENC[AES256_GCM,data:o0HND8CKxDss8shv4V+Jz75X8Yv3sRY2YYX5CNUW3oN/OFA57ycdeLuu2xEd4N3QfgQfsjwsZTmfNt+PCwwBsQ==,iv:GqfY/aPh5MgyQ6hv/qMxyspNLY4KrMXsjNG3kxumGms=,tag:FLUqwsdDvxYWoEH/yw3IMA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQajJmUVBzQXdLSTNUanla
        NU1saS82Sit3aXIyYmY3dzR2cmxRbmtHUG5rCm1abGRXMmtudlp2VHY3MFRkMzE5
        Tk5FSnZYRHJtT3BTZ0JoTVdjakJxN2MKLS0tIHllS3lYaFpwVUdSeldmbnVTb3d5
        MnZrVVpNYnNqMmxpakRlQUYxOGQ3R00KtKdpP1J6hopqAXJ4zrvj4u8LBJTJIHxJ
        4Dx3pysOn99O/sh04Ut2BBHa5GSshUVa2J6ZombUpJUrBvh4TLjLxQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-12T18:32:57Z"
  mac: ENC[AES256_GCM,data:RaYHFht67ZvY6e1ohwLW5pmxM36xfR3luLxh3GqDQTvXWUpT79cis5O8xUxZNQ9lsRwgKDj1dxwliPfZzxwsB0/wi+n8U+ELZPshojaIuMd9m6S0yXNJkfw5d6GGa4OqznUyFPJC91Grf/E/rINPHkRw6WQj+3d9anDkjYwmvOk=,iv:HHVwKapnxkmykCxnVYHPeEiq8MJZnwuG5KK1/8pLiW8=,tag:Przb09rs4P3CuAsB+D38uA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
