apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
  namespace: auth
type: Opaque
stringData:
  secret_key: ENC[AES256_GCM,data:t96o750qn3Wcva9fyez/H0Md9KpcVOesanjZVCRnrsfoXuZ8TtZggaIfXHYyTcREVI997cw5PXwjAbymXnBJtg==,iv:rdE7y6YpOBMCH7I0H+QkgpdpWTgoXz92RrqRv3zr/zw=,tag:UGmohDHOVyU3pM/wSnTurg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRHlnQkVWMGRYS0xvSUZN
        YWw3R1cwY1NId0FiaVJnb0c1cXdUUmNMM0J3CkhCOEt0VTlURVA2RCtGMDFWWlVa
        dXprdXhucFdocGp1aUFwK21FYUJad0kKLS0tIDdEelZVMi9jNTlnWE1HV3hHZEZv
        c0toNlc1WTJqQkd3M3JYNlZKcmpLV1UKnb2R01mGieWQlbDbr/O1AwJ0IeBrCJf5
        PTjPVcVlHBXZ/FSyXdbRNMFCDBDkKH4m7Jd+BFCs+YrB8IL1k20qjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-12T18:31:59Z"
  mac: ENC[AES256_GCM,data:Dt5Lr2xTlyE53a0EgECKib/w/RjpA1uD9cSqiKofD5QklHlBxSpCpDj5d9i3H50pEMIXsldeDnWvBWhOkGQyTRJV60jTDjmSMBSDttIgMoW3TFt1YMur2VgushGhKiEUiCtyu2oDC049Sn65+c5Mvyjl4ld93fFR02sndQ/HsDU=,iv:fbfW8sHpUYq0r0xUamUNTmU0fmI4gRpcqyZNd7yDWEs=,tag:+rwxI88GuS+2WcxSPJYJQQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
