apiVersion: v1
kind: Secret
metadata:
  name: trek-admin-secret
  namespace: travel
type: Opaque
stringData:
  ADMIN_PASSWORD: ENC[AES256_GCM,data:lVUx2yviV5UIYQuS51Xj/amXBF32qrtaEJPlLxY4zXjuMv8Pc8EoH/20KtK7k4/5VTAFhlYOGmCVkJopoDwfTg==,iv:8mMxcDgfKNegSidElD1X9D2DmZgbrK4O4Dk5bJVyi1M=,tag:r30yZE9Zox1r1+UifdPsXg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxR3NGYzdFTW5UalZWa2M5
        bi9HVnByQmR3bTFIckt1WkFCMU81N1VGT0JJCkVKT0FYQ3hwM09rMzRhUkdkb1R2
        ams0eGRlMTREK0JxQ2ZQS2JSaGJuUFUKLS0tIGlpNzI4YTdEMS9OQ2xxekJWRzBY
        eUYxOVJYQjRhZWFpcnpHRzlaUkE4OTAK5FZ1WG+hMd4K7QMkIy1qHhr0tMgLzwvw
        vpwkw/gnSJ34Nissrwo5VrDATH0o/BzS4g5ieUcJBHIfMqTatlDIPQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-24T10:43:42Z"
  mac: ENC[AES256_GCM,data:LTWc27kHv+feQ3OK99ujuOetFnzlxB5rNjtkQYvXmAqEP557SK/Te5l5EQbPibPBBl3wgI8mdc4F/h0speFlvF320x3zHCqiq8A2SkbZz+I3/HjX5U51KvH/6LIVjP/8XrggJQOJrsLbUDtxaYCMdGdjhIQxjZK/etvtgJ+Edws=,iv:LVoXLypj29EOSHGzovbCTEI/6et6fRcHO8DjXwZi5/E=,tag:MQbfn8TBGffMscDlPqL09A==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
