apiVersion: v1
kind: Secret
metadata:
  name: trek-encryption-secret
  namespace: travel
type: Opaque
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:s/6hcxsPkdVkrUuyZaghPAp6WuMTevXGnS5Vb74QAaAqiq3l0ADQX2jMxGjrVo4w7RjrUoCmuCW0KzHyiHZaGA==,iv:zaB5gtPJsysyOqsN9UckIesxwbRF0nz9v09YcnevCx0=,tag:eFx4oDiy0xW8JblIaGhyTg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQldCZVFXOGhtNE1jeitk
        Qlh0NVI5TXZDZ1VKbVY1L2lpV1l1YVdkc0FVClk1U1BVMnNyQkt5SkY2TlA0Visx
        M05KMFF5NzJsYlprZU9vbktTcnJ2N3MKLS0tIGtFVjFaYzQzUDc5Z1MyVG8wd2Jr
        N3lYdHE2c2RBY2VRZmZDN01BOEZ3M00KDJu3lCTZgs//CmSshTESOpwJZcmrFipb
        Cq17tUeeTYSGhcz3fs6KoDqPx1KRipa07Pwu44AbEdAZZvRk2pcDuQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-24T10:44:50Z"
  mac: ENC[AES256_GCM,data:uAeRIbotAoZda4a8omsdkhv0CbHxfhL1GEHbisgatcQj2WK3bRZCNmt3rhF12V7gviKego3xSbCxt7ahWl78lYTI0FkfdjzEYk6aDZqsKkHx6GnNJh3hzbC83UxqVeea+EwQT/SxMrLv3igJ4s3AO34r8erSEaBwX7Hq1kpc3+M=,iv:sm95wq5MAnrGi74IlnX2MlyOzJM5HiQxKK8iqVfQ4Xo=,tag:SLEMd0Gz/mSVfzhw0vNKtw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
