apiVersion: v1
kind: Secret
metadata:
  name: trek-oidc-credentials
  namespace: travel
type: Opaque
stringData:
  client_secret: ENC[AES256_GCM,data:fY6lurjOepKjHKUeuEFa1Ug3kD9VB0zy0C6T+KQW5rLokf3pcLcJSd25wARJyUsac8zuKepcotSDWGTuNvEU3Q==,iv:4tBmAKW4XrcaS/zt0Hh4+v7ppwor6Xd5iihF1IqLgrs=,tag:pJWZG+tW+7nYwkYPs7gmUQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdjF3Tk9mYlF5L0JBOHZp
        ZFFwUHZXVWk2V3Q2b29FRkx3ditMZXZHVmxZCjU2OWRIcC9DNC9aTlE4R2NzWi9v
        WmtrNytVWHVQR1A0UlhJSGdIbGtzdG8KLS0tIHkvOGhXSEhmS3dHRk82N0NVbGZk
        RFE1QTZUTmhNcWRKeXZxaEdRNTV4UlUKbkLa9Z+Evf+w62gCVmaEvDA2bLRE+/ZM
        nBncK2c/f13wwRCo+feG7ORqINW4rKzEfBgC4JUmqkHFAHeYsLFWZg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-24T11:04:13Z"
  mac: ENC[AES256_GCM,data:uI6Mokn849XZJrbsiJDdNbEFTfSqDYAsiHEqs7+URVMPSXd22D0MRrCX55Ux1SCJ1VZ2LE5yrAm4RTCyJJG7f3JyDbwI9GzKHIm5YiPn+aoBTVFwBS54eGcaYnKn58Rna8k/MJowOz8Pygpo5pXb4M2BP9r63GDLFgxFIitbDa4=,iv:v2Dy1FDG5O5D+Z3PYuQ/D3hat3SA7Udsw6GJH2q9obM=,tag:SR+LwRGFfmaixF3RbKTsLQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
