apiVersion: v1
kind: Secret
metadata:
  name: trek-oidc-credentials
  namespace: travel
type: Opaque
stringData:
  client_secret: ENC[AES256_GCM,data:mAfX7QN9ZmMUKjxM9u92dbGYrNXy9aGq7RU2/e24nLbMWiWq1SUpmSaXXT44gvRu9ABc3gJeh8esf1xcJuZhEw==,iv:h+f3uqellYpH+v8D45UKG8lBQSn6E452xfbMyef0SnY=,tag:Kax3ZNFhCV4oX5WRPawZ4Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdjF3Tk9mYlF5L0JBOHZp
        ZFFwUHZXVWk2V3Q2b29FRkx3ditMZXZHVmxZCjU2OWRIcC9DNC9aTlE4R2NzWi9v
        WmtrNytVWHVQR1A0UlhJSGdIbGtzdG8KLS0tIHkvOGhXSEhmS3dHRk82N0NVbGZk
        RFE1QTZUTmhNcWRKeXZxaEdRNTV4UlUKbkLa9Z+Evf+w62gCVmaEvDA2bLRE+/ZM
        nBncK2c/f13wwRCo+feG7ORqINW4rKzEfBgC4JUmqkHFAHeYsLFWZg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-24T13:32:30Z"
  mac: ENC[AES256_GCM,data:M8+O8+/aeIA03xBYhhp/lspjYZgVi5b8w5ero7c1jHThjc7dtC0zT7juMzDvc8Gy/I/BE4b9kL97I6cGaFCQjgDybtZ8opEdqC++sQk29EwoE83YOdPvNZszRAWHmAiFMg8Eh7R8BqlRgK+CZpnr5jDHUbEK5XVFiJxEGcnNYgg=,iv:cT4rSYbgU6jv+EZ3YvM/GgyPc1UwR0+jNVcw22WXms4=,tag:DU7SLAh7gHa+Tf9mpqrS1Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
