apiVersion: v1
kind: Secret
metadata:
  name: trek-smtp-secret
  namespace: travel
type: Opaque
stringData:
  SMTP_PASSWORD: ENC[AES256_GCM,data:khdMzTk13JzejRYTbEJYTI4PUBw=,iv:/UNyblGSUqQcNFKhZibVAzHKXd4zwynGyMNGygETIxU=,tag:9Ep4QEGuwJEeIKIYJWI0vg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZVBQK0p4VmNqdE5nU2Qv
        MWV6OFdQcnhWVE1nZUI0SFREL3RVWUNKOFNBClRQUGlrMHVqOHlYWUN6MWRiQWw2
        N04vS1czMXB4ZmVSNldTUjVuZlR4cDQKLS0tIElaWjBOYkM5eHNhMGl3eTYrOEF0
        T1FCaHpNUTJKcllVa1R0enRJaFJKZWcK/Ryx1b+cRFkZnh/m0B4zOAiSbo8TrOyS
        gTZyzJnfcADr3slBRXEhVrHVNd3ELZCKvhXm36c5mXjYNz0OfvVDJA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1zrwh8ph6gq4r9qzz6627c0v6cucvqfu37drj0q8pjlxk0rfu3szqx4v68a
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-24T11:15:47Z"
  mac: ENC[AES256_GCM,data:LwDCzDPVCMJQn6XjQA+RmujE2V/qWlIC4K35+nvtPs/kTxqpX2lMtvmxQRMtXQWowDVoOUc95vRWmNNxkpNZV4Ks0UEKIsPizP4eIO9P3TBFgxbTH7mNXxONyCqpom9CeYai4ZVQ4bPIN8WcMEciUogRQH2xDLOrLCMo7KWjBYE=,iv:1bfWdCuUfFWylvrjsfoiemwnER7NtGv6YJIoyar1a6A=,tag:MkbE46UP+zyQ80UO349FUg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
