---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth

resources:
  - ./auth-authentik-worker-allow-eg-to-db-pg-authentik.yaml
  - ./auth-authentik-worker-allow-eg-to-coredns.yaml
  - ./auth-authentik-worker-allow-ig-from-prometheus.yaml
  - ./auth-authentik-worker-allow-eg-to-world.yaml
  - ./auth-authentik-worker-allow-ig-from-envoy-gateway.yaml